services:
  mongo:
    image: mongo:7
    container_name: kiki-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  frontend:
    build: ./frontend
    container_name: kiki-frontend
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: kiki-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - frontend

  # backend:
  #   build: ./backend
  #   container_name: kiki-backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017
  #   volumes:
  #     - ./media:/app/media
  #   depends_on:
  #     - mongo

volumes:
  mongo-data:
  caddy-data:
  caddy-config:
